version: '2'

services:
  app:
    build:
      context: ./app
      dockerfile: app.dockerfile
      args:
        ENVIRONMENT: development
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - ./app/:/app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  celery:
    build:
      context: ./app
      dockerfile: celery.dockerfile
      args:
        ENVIRONMENT: development
    env_file:
      - .env
    restart: always
    depends_on:
      - app
      - redis
    volumes:
      - ./app/:/app
    command: "watchmedo auto-restart --recursive -d app/ -p '*.py' -- celery -A app.celery_app worker --loglevel=DEBUG"

  celery-beat:
    build:
      context: ./app
      dockerfile: celery_beat.dockerfile
      args:
        ENVIRONMENT: development
    env_file:
      - .env
    restart: always
    depends_on:
      - app
      - redis
    volumes:
      - ./app/:/app
    command: "watchmedo auto-restart --recursive -d app/ -p '*.py' -- celery -A app.celery_app beat --loglevel=DEBUG"

  postgres:
    ports:
      - "8046:5432"
    build:
      context: ./database
      dockerfile: database.dockerfile
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  proxy:
    ports:
      - "8045:80"
    build:
      context: ./proxy
      dockerfile: proxy.dockerfile
    depends_on:
      - app

  redis:
    image: redis:latest

networks:
  default:

volumes:
  app-postgres-data: