FROM python:3.10.15-slim-bullseye

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml /app/

RUN poetry install --no-root

COPY . /app

CMD ["sleep" , "infinity"]
#CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]