"""

Revision ID: 213794a80fa0
Revises: d31a197af1c6
Create Date: 2024-12-09 19:50:00.742321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213794a80fa0'
down_revision = 'd31a197af1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_is_embeddings_dirty'), 'item', ['is_embeddings_dirty'], unique=False)
    op.create_index(op.f('ix_item_is_index_dirty'), 'item', ['is_index_dirty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_is_index_dirty'), table_name='item')
    op.drop_index(op.f('ix_item_is_embeddings_dirty'), table_name='item')
    # ### end Alembic commands ###
