"""

Revision ID: 21e9ade94fca
Revises: 774665f41853
Create Date: 2024-06-07 12:24:40.835788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e9ade94fca'
down_revision = '774665f41853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_related_recommendation_id'), 'event', ['related_recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_related_recommendation_id'), table_name='event')
    # ### end Alembic commands ###
