"""Initial models

Revision ID: 442c93ca86b9
Revises: 61cdf3c7c7db
Create Date: 2024-04-10 18:51:48.967082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442c93ca86b9'
down_revision = '61cdf3c7c7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
