"""

Revision ID: 56e87318c063
Revises: a436a6bd74f2
Create Date: 2024-05-09 07:28:11.190002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e87318c063'
down_revision = 'a436a6bd74f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_created'), 'event', ['created'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_search_history_created'), 'search_history', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_created'), table_name='search_history')
    op.create_index('item_vectors_1536_idx', 'item', ['vectors_1536'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_created'), table_name='event')
    # ### end Alembic commands ###
