"""

Revision ID: 5eb4d80fff4f
Revises: a289a2fda5a1
Create Date: 2024-11-15 21:03:27.767698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb4d80fff4f'
down_revision = 'a289a2fda5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('_config', sa.JSON(), nullable=True))
    op.drop_column('collection', 'default_embeddings_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('default_embeddings_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('collection', '_config')
    # ### end Alembic commands ###
