"""Initial models

Revision ID: 61cdf3c7c7db
Revises: 
Create Date: 2024-04-10 18:42:19.996743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = '61cdf3c7c7db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fields_hash', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('vectors_1536', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'collection_id')
    )
    op.create_index(op.f('ix_item_external_id'), 'item', ['external_id'], unique=False)
    op.create_table('items_field',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('order', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'collection_id'),
    sa.UniqueConstraint('collection_id', 'field_name')
    )
    op.create_table('person',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'collection_id')
    )
    op.create_index(op.f('ix_person_external_id'), 'person', ['external_id'], unique=False)
    op.create_table('persons_field',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('order', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'collection_id'),
    sa.UniqueConstraint('collection_id', 'field_name')
    )
    op.create_table('recommendation_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_person_id', sa.String(), nullable=True),
    sa.Column('external_item_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_history_external_item_ids'), 'recommendation_history', ['external_item_ids'], unique=False)
    op.create_index(op.f('ix_recommendation_history_external_person_id'), 'recommendation_history', ['external_person_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('person_external_id', sa.String(), nullable=True),
    sa.Column('item_external_id', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('related_recommendation_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_recommendation_id'], ['recommendation_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_index(op.f('ix_recommendation_history_external_person_id'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_external_item_ids'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    op.drop_table('persons_field')
    op.drop_index(op.f('ix_person_external_id'), table_name='person')
    op.drop_table('person')
    op.drop_table('items_field')
    op.drop_index(op.f('ix_item_external_id'), table_name='item')
    op.drop_table('item')
    op.drop_table('collection')
    op.drop_table('organization')
    # ### end Alembic commands ###
