"""

Revision ID: 6d360ddcaa20
Revises: 442c93ca86b9
Create Date: 2024-04-16 17:08:09.914969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d360ddcaa20'
down_revision = '442c93ca86b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.String(), nullable=True))
    op.add_column('item', sa.Column('description_hash', sa.String(), nullable=True))
    op.drop_column('item', 'fields_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('fields_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('item', 'description_hash')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
