"""

Revision ID: 774665f41853
Revises: 78752a3695cb
Create Date: 2024-05-27 13:23:08.871944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774665f41853'
down_revision = '78752a3695cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_search_history_collection_id'), 'search_history', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_collection_id'), table_name='search_history')
    # ### end Alembic commands ###
