"""

Revision ID: a289a2fda5a1
Revises: 21e9ade94fca
Create Date: 2024-11-06 10:55:46.897663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a289a2fda5a1'
down_revision = '21e9ade94fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('item_description_idx', 'item', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('item_vectors_1536', 'item', ['vectors_1536'], unique=False, postgresql_ops={'vectors_1536': 'vector_l2_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('item_vectors_1536', table_name='item', postgresql_ops={'vectors_1536': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.drop_index('item_description_idx', table_name='item', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
