"""

Revision ID: a436a6bd74f2
Revises: af6e3c420622
Create Date: 2024-04-17 09:02:32.085720

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'a436a6bd74f2'
down_revision = 'af6e3c420622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('vectors_3072', pgvector.sqlalchemy.Vector(dim=3072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'vectors_3072')
    # ### end Alembic commands ###
