"""

Revision ID: c22bf5d01ff5
Revises: 29ccb3753028
Create Date: 2024-11-24 20:53:53.350212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22bf5d01ff5'
down_revision = '29ccb3753028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('embeddings_dirty', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('indexed_dirty', sa.Boolean(), nullable=True))
    op.drop_column('item', 'is_dirty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_dirty', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('item', 'indexed_dirty')
    op.drop_column('item', 'embeddings_dirty')
    # ### end Alembic commands ###
