"""

Revision ID: d31a197af1c6
Revises: d59345b64005
Create Date: 2024-12-09 14:38:44.559448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31a197af1c6'
down_revision = 'd59345b64005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('is_index_dirty', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('is_embeddings_dirty', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('is_index_dirty', sa.Boolean(), nullable=True))
    op.drop_column('item', 'indexed_dirty')
    op.drop_column('item', 'embeddings_dirty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('embeddings_dirty', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('indexed_dirty', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('item', 'is_index_dirty')
    op.drop_column('item', 'is_embeddings_dirty')
    op.drop_column('collection', 'is_index_dirty')
    # ### end Alembic commands ###
