"""

Revision ID: d59345b64005
Revises: 8baab0c42e3a
Create Date: 2024-12-08 22:36:02.203764

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'd59345b64005'
down_revision = '8baab0c42e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('vectors_384', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'vectors_384')
    # ### end Alembic commands ###
